import { ActionVersion, HttpMethod, SessionType } from '@diia-inhouse/types'

import { DEFAULT_USER_AUTH, DEFAULT_USER_HEADERS } from './defaults'

import { RouteHeaderRawName } from '@interfaces/index'
import { AppRoute } from '@interfaces/routes/appRoute'
import { PartnerMaintenanceScope, PartnerScopeType } from '@interfaces/routes/partner'

enum ServiceActions {
    GetDamagedPropertyServiceInfo = 'getDamagedPropertyServiceInfo',
    GetDamagedPropertyApplicationInfo = 'getDamagedPropertyApplicationInfo',
    GetDamagedPropertyTypes = 'getDamagedPropertyTypes',
    GetDamagedPropertyProperties = 'getDamagedPropertyProperties',
    GetDamagedPropertyRealEstateDescription = 'getDamagedPropertyRealEstateDescription',
    GetDamagedPropertyLosses = 'getDamagedPropertyLosses',
    GetDamagedPropertyDamaging = 'getDamagedPropertyDamaging',
    GetDamagedPropertyContacts = 'getDamagedPropertyContacts',
    GetDamagedPropertyApplicationDetails = 'getDamagedPropertyApplicationDetails',
    SendDamagedPropertyApplication = 'sendDamagedPropertyApplication',
    DownloadDamagedPropertyApplication = 'downloadDamagedPropertyApplication',

    GetDamagedPropertyRecoveryServiceInfo = 'getDamagedPropertyRecoveryServiceInfo',
    GetDamagedPropertyRecoveryRelatedDocuments = 'getDamagedPropertyRecoveryRelatedDocuments',
    GetDamagedPropertyRecoveryDamageMessages = 'getDamagedPropertyRecoveryDamageMessages',
    GetDamagedPropertyRecoveryDamageMessage = 'getDamagedPropertyRecoveryDamageMessage',
    GetDamagedPropertyRecoveryBindRealtyInfo = 'getDamagedPropertyRecoveryBindRealtyInfo',
    GetDamagedPropertyRecoveryDrrpRealties = 'getDamagedPropertyRecoveryDrrpRealties',
    BindDamagedPropertyRecoveryRealty = 'bindDamagedPropertyRecoveryRealty',
    GetDamagedPropertyRecoveryNewApplication = 'getDamagedPropertyRecoveryNewApplication',
    GetDamagedPropertyRecoveryCompensationTypes = 'getDamagedPropertyRecoveryCompensationTypes',
    GetDamagedPropertyRecoveryPropertyRepair = 'getDamagedPropertyRecoveryPropertyRepair',
    GetDamagedPropertyRecoveryBenefits = 'getDamagedPropertyRecoveryBenefits',
    GetDamagedPropertyRecoveryBenefitsConfirmation = 'getDamagedPropertyRecoveryBenefitsConfirmation',
    GetDamagedPropertyRecoveryContacts = 'getDamagedPropertyRecoveryContacts',
    CreateDamagedPropertyRecoveryApplication = 'createDamagedPropertyRecoveryApplication',
    GetDamagedPropertyRecoveryOwnersConfirmation = 'getDamagedPropertyRecoveryOwnersConfirmation',
    ConfirmDamagedPropertyRecoveryOwners = 'confirmDamagedPropertyRecoveryOwners',
    ShareDamagedPropertyRecoveryApplication = 'shareDamagedPropertyRecoveryApplication',
    VerifyDamagedPropertyRecoveryApplication = 'verifyDamagedPropertyRecoveryApplication',
    ConfirmDamagedPropertyRecoveryApplicationOffline = 'confirmDamagedPropertyRecoveryApplicationOffline',
    ConfirmDamagedPropertyRecoveryApplicationRefusal = 'confirmDamagedPropertyRecoveryApplicationRefusal',
    ConfirmDamagedPropertyRecoveryApplication = 'confirmDamagedPropertyRecoveryApplication',
    RejectDamagedPropertyRecoveryApplication = 'rejectDamagedPropertyRecoveryApplication',
    GetDamagedPropertyRecoveryBankAccounts = 'getDamagedPropertyRecoveryBankAccounts',
    GetDamagedPropertyRecoveryBanks = 'getDamagedPropertyRecoveryBanks',
    UpdateDamagedPropertyRecoveryApplication = 'updateDamagedPropertyRecoveryApplication',
    GetDamagedPropertyRecoveryApplicationToConfirm = 'getDamagedPropertyRecoveryApplicationToConfirm',
    SendDamagedPropertyRecoveryApplication = 'sendDamagedPropertyRecoveryApplication',
    GetDamagedPropertyRecoveryApplication = 'getDamagedPropertyRecoveryApplication',
    CancelDamagedPropertyRecoveryApplication = 'cancelDamagedPropertyRecoveryApplication',
    DownloadDamagedPropertyRecoveryDocument = 'downloadDamagedPropertyRecoveryDocument',

    GetHousingCertificatesServiceInfo = 'getHousingCertificatesServiceInfo',
    GetHousingCertificateDetails = 'getHousingCertificateDetails',
    OrderHousingCertificateDocument = 'orderHousingCertificateDocument',
    GetHousingCertificateDocument = 'getHousingCertificateDocument',
    GetHousingCertificateFundingRequestOnboarding = 'getHousingCertificateFundingRequestOnboarding',
    GetHousingCertificateFundingRequestCertificates = 'getHousingCertificateFundingRequestCertificates',
    CreateHousingCertificateFundingRequest = 'createHousingCertificateFundingRequest',
    GetHousingCertificateFundingRequestConfirmation = 'getHousingCertificateFundingRequestConfirmation',
    SendHousingCertificateFundingRequest = 'sendHousingCertificateFundingRequest',
    CancelHousingCertificateFundingRequest = 'cancelHousingCertificateFundingRequest',

    GetDamagedPropertyRecoveryRepairCompletionMessage = 'getDamagedPropertyRecoveryRepairCompletionMessage',
    SubmitDamagedPropertyRecoveryRepairCompletionMessage = 'submitDamagedPropertyRecoveryRepairCompletionMessage',
    GetDamagedPropertyRecoveryRepairCompletionMessageMediaUpload = 'getDamagedPropertyRecoveryRepairCompletionMessageMediaUpload',
    SendDamagedPropertyRecoveryRepairCompletionMessage = 'sendDamagedPropertyRecoveryRepairCompletionMessage',

    GetDamagedPropertyUserInitiativeRatingForm = 'getDamagedPropertyUserInitiativeRatingForm',
    GetDamagedPropertyRecoveryUserInitiativeRatingForm = 'getDamagedPropertyRecoveryUserInitiativeRatingForm',
    GetMonetaryCompensationUserInitiativeRatingForm = 'getMonetaryCompensationUserInitiativeRatingForm',
    GetReparationsUserInitiativeRatingForm = 'getReparationsUserInitiativeRatingForm',
}

const serviceId = 'property-node'

const routes: AppRoute[] = [
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property',
        action: ServiceActions.GetDamagedPropertyServiceInfo,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/application/:applicationId',
        action: ServiceActions.GetDamagedPropertyApplicationInfo,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/types',
        action: ServiceActions.GetDamagedPropertyTypes,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/:type',
        action: ServiceActions.GetDamagedPropertyProperties,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/real-estate/description',
        action: ServiceActions.GetDamagedPropertyRealEstateDescription,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/:type/losses',
        action: ServiceActions.GetDamagedPropertyLosses,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/:type/damaging',
        action: ServiceActions.GetDamagedPropertyDamaging,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/contacts',
        action: ServiceActions.GetDamagedPropertyContacts,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property/application',
        action: ServiceActions.GetDamagedPropertyApplicationDetails,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property/application/send',
        action: ServiceActions.SendDamagedPropertyApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property/application/:applicationId/download',
        action: ServiceActions.DownloadDamagedPropertyApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },

    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery',
        action: ServiceActions.GetDamagedPropertyRecoveryServiceInfo,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
            { sessionType: SessionType.User, version: ActionVersion.V4 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2, ActionVersion.V3, ActionVersion.V4] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2, ActionVersion.V3, ActionVersion.V4] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2, ActionVersion.V3, ActionVersion.V4] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2, ActionVersion.V3, ActionVersion.V4] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/related-documents/:propertyId',
        action: ServiceActions.GetDamagedPropertyRecoveryRelatedDocuments,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/damage-messages',
        action: ServiceActions.GetDamagedPropertyRecoveryDamageMessages,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/damage-message/:applicationId',
        action: ServiceActions.GetDamagedPropertyRecoveryDamageMessage,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/bind-realty',
        action: ServiceActions.GetDamagedPropertyRecoveryBindRealtyInfo,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/drrp-realties',
        action: ServiceActions.GetDamagedPropertyRecoveryDrrpRealties,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/bind-realty',
        action: ServiceActions.BindDamagedPropertyRecoveryRealty,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/new-application/:propertyId',
        action: ServiceActions.GetDamagedPropertyRecoveryNewApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/compensation-type',
        action: ServiceActions.GetDamagedPropertyRecoveryCompensationTypes,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/property-repair/:propertyId',
        action: ServiceActions.GetDamagedPropertyRecoveryPropertyRepair,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/benefits/:propertyId',
        action: ServiceActions.GetDamagedPropertyRecoveryBenefits,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/benefits-confirmation',
        action: ServiceActions.GetDamagedPropertyRecoveryBenefitsConfirmation,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/contacts',
        action: ServiceActions.GetDamagedPropertyRecoveryContacts,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application',
        action: ServiceActions.CreateDamagedPropertyRecoveryApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V2 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/owners-confirmation',
        action: ServiceActions.GetDamagedPropertyRecoveryOwnersConfirmation,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/owners-confirmation',
        action: ServiceActions.ConfirmDamagedPropertyRecoveryOwners,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/share',
        action: ServiceActions.ShareDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/verify',
        action: ServiceActions.VerifyDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/confirm-offline',
        action: ServiceActions.ConfirmDamagedPropertyRecoveryApplicationOffline,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/confirm-refusal',
        action: ServiceActions.ConfirmDamagedPropertyRecoveryApplicationRefusal,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/confirm',
        action: ServiceActions.ConfirmDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/reject',
        action: ServiceActions.RejectDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/bank-accounts',
        action: ServiceActions.GetDamagedPropertyRecoveryBankAccounts,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/banks',
        action: ServiceActions.GetDamagedPropertyRecoveryBanks,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId',
        action: ServiceActions.UpdateDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/confirmation',
        action: ServiceActions.GetDamagedPropertyRecoveryApplicationToConfirm,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId/send',
        action: ServiceActions.SendDamagedPropertyRecoveryApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId',
        action: ServiceActions.GetDamagedPropertyRecoveryApplication,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V2 },
            { sessionType: SessionType.User, version: ActionVersion.V3 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V2, ActionVersion.V3] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V2, ActionVersion.V3] },
        ],
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:applicationId',
        action: ServiceActions.CancelDamagedPropertyRecoveryApplication,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/:applicationId/:documentType/download',
        action: ServiceActions.DownloadDamagedPropertyRecoveryDocument,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/application/:id/bank-accounts/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },

    // Housing Certificates
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates',
        action: ServiceActions.GetHousingCertificatesServiceInfo,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates/certificate/:id',
        action: ServiceActions.GetHousingCertificateDetails,
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates/certificate/:id/download',
        action: ServiceActions.GetHousingCertificateDocument,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/housing-certificates/certificate/:id/order',
        action: ServiceActions.OrderHousingCertificateDocument,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request/onboarding',
        action: ServiceActions.GetHousingCertificateFundingRequestOnboarding,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request/certificates',
        action: ServiceActions.GetHousingCertificateFundingRequestCertificates,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request',
        action: ServiceActions.CreateHousingCertificateFundingRequest,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request/:id/confirmation',
        action: ServiceActions.GetHousingCertificateFundingRequestConfirmation,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request/:id/send',
        action: ServiceActions.SendHousingCertificateFundingRequest,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/housing-certificates/funding-request/:id',
        action: ServiceActions.CancelHousingCertificateFundingRequest,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },

    // Monetary Compensation
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/onboarding',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/onboarding/:id',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/compensation/:id',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-start-message/:id',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/contacts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-start-message/:id/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-completion-message/:id',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-completion-message/:id',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-completion-message/media-upload',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/monetary-compensation/constructing-completion-message/:id/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/bank-accounts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/monetary-compensation/banks',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/monetary-compensation/:id/bank-accounts/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
    },

    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/repair-completion-message/:applicationId',
        action: ServiceActions.GetDamagedPropertyRecoveryRepairCompletionMessage,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/repair-completion-message/:applicationId',
        action: ServiceActions.SubmitDamagedPropertyRecoveryRepairCompletionMessage,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/repair-completion-message/media-upload',
        action: ServiceActions.GetDamagedPropertyRecoveryRepairCompletionMessageMediaUpload,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/repair-completion-message/:applicationId/send',
        action: ServiceActions.SendDamagedPropertyRecoveryRepairCompletionMessage,
        auth: [{ sessionType: SessionType.User, version: ActionVersion.V1 }],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1] },
        ],
    },

    // Reparations
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/onboarding',
        proxyTo: { serviceId },
        auth: [
            { sessionType: SessionType.User, version: ActionVersion.V1 },
            { sessionType: SessionType.User, version: ActionVersion.V2 },
        ],
        headers: [
            { name: RouteHeaderRawName.MOBILE_UID, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.APP_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_TYPE, versions: [ActionVersion.V1, ActionVersion.V2] },
            { name: RouteHeaderRawName.PLATFORM_VERSION, versions: [ActionVersion.V1, ActionVersion.V2] },
        ],
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/object',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/ownerships',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/object-area',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/residence',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/damage',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/damage',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/acts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/compensation',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/compensation',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/registration-confirm',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/registration-confirm',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/registration',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/contacts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/contacts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info/group',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info/group',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info/:groupId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/additional-info/submit',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/confirmation',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/signing',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/object-without-act',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/refuse',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/download/pdf',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/download/files',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/onboarding/withdraw',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/withdraw/signing',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/withdraw/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/documents/download',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/onboarding/adding',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/adding/additional-info',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/application/adding/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/adding/additional-info/group',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/adding/additional-info',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/adding/additional-info/group',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/reparations/:applicationId/adding/additional-info/:groupId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/adding/signing',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId/adding/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/v1/public-service/reparations/repair',
        proxyTo: { serviceId: 'diia-international-claim-integration' },
        auth: [
            {
                sessionType: SessionType.Partner,
                version: ActionVersion.V1,
                scopes: {
                    [PartnerScopeType.maintenance]: [PartnerMaintenanceScope.Admin],
                },
            },
        ],
    },

    // reparations v2
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/applications',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/reparations/application/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Reparations'] },
    },

    // Rating
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/analytics/service-rating/public-service/damaged-property/rating-form',
        action: ServiceActions.GetDamagedPropertyUserInitiativeRatingForm,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: {
            tags: ['Rating'],
        },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/analytics/service-rating/public-service/damaged-property-recovery/rating-form',
        action: ServiceActions.GetDamagedPropertyRecoveryUserInitiativeRatingForm,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: {
            tags: ['Rating'],
        },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/analytics/service-rating/public-service/monetary-compensation/rating-form',
        action: ServiceActions.GetMonetaryCompensationUserInitiativeRatingForm,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: {
            tags: ['Rating'],
        },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/analytics/service-rating/public-service/reparations/rating-form',
        action: ServiceActions.GetReparationsUserInitiativeRatingForm,
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: {
            tags: ['Rating'],
        },
    },

    // Temporary occupied territories whitelist
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/tot/whitelist',
        proxyTo: { serviceId },
        auth: [
            {
                sessionType: SessionType.Partner,
                version: ActionVersion.V1,
                scopes: {
                    [PartnerScopeType.maintenance]: [PartnerMaintenanceScope.Admin],
                },
            },
        ],
        metadata: {
            tags: ['Temporary occupied territories whitelist'],
        },
    },
    {
        method: HttpMethod.DELETE,
        path: '/api/:apiVersion/public-service/damaged-property-recovery/tot/whitelist',
        proxyTo: { serviceId },
        auth: [
            {
                sessionType: SessionType.Partner,
                version: ActionVersion.V1,
                scopes: {
                    [PartnerScopeType.maintenance]: [PartnerMaintenanceScope.Admin],
                },
            },
        ],
        metadata: {
            tags: ['Temporary occupied territories whitelist'],
        },
    },
]

export default routes
