import { HttpMethod } from '@diia-inhouse/types'

import { DEFAULT_USER_AUTH, DEFAULT_USER_HEADERS } from '@src/routes/defaults'

import { AppRoute } from '@interfaces/routes/appRoute'

const serviceId = 'medical'

const routes: AppRoute[] = [
    // declarations
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/onboarding',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/layout',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.PATCH,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/:applicationId',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/choice-person-type',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/choice-person',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/verify-person',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/choice-division',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/divisions-layout',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/divisions',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/choice-doctor',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/create',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/:applicationId/confirm',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/:applicationId/signing',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/declarations/applications/:applicationId/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Declarations'] },
    },

    // person registration
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/persons/registration/secret',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/persons/registration/contacts',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.GET,
        path: '/api/:apiVersion/public-service/medical/persons/registration/emergency-contact',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/registration/otp',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/registration/confirm',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/registration/signing',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/registration/send',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons registration'] },
    },

    // person data
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/data/home',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons data'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/data/profile',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons data'] },
    },
    {
        method: HttpMethod.POST,
        path: '/api/:apiVersion/public-service/medical/persons/data/identity',
        proxyTo: { serviceId },
        auth: DEFAULT_USER_AUTH,
        headers: DEFAULT_USER_HEADERS,
        metadata: { tags: ['Persons data'] },
    },
]

export default routes
