import { ActionVersion, HttpMethod, SessionType } from '@diia-inhouse/types'

import { DEFAULT_USER_AUTH, DEFAULT_USER_HEADERS } from '@src/routes/defaults'

import { AppRoute } from '@interfaces/routes/appRoute'
import { PartnerMortgageScope, PartnerScopeType } from '@interfaces/routes/mortgage'

enum ServiceActions {
    GetMortgageServiceInfo = 'getMortgageServiceInfo',
    GetMortgageCategories = 'getMortgageCategories',
    GetMortgageMaritalStatus = 'getMortgageMaritalStatus',
    CreateMortgagePackage = 'createMortgagePackage',
    ShareMortgage = 'shareMortgage',
    VerifyMortgage = 'verifyMortgage',
    RejectMortgage = 'rejectMortgage',
    GetMortgageChildrenNumber = 'getMortgageChildrenNumber',
    SetMortgageChildrenNumber = 'setMortgageChildrenNumber',
    GetMortgageChildren = 'getMortgageChildren',
    SetMortgageChildren = 'setMortgageChildren',
    GetMortgageRealEstate = 'getMortgageRealEstate',
    GetMortgageManualRealEstate = 'getMortgageManualRealEstate',
    GetMortgageIncome = 'getMortgageIncome',
    SetMortgageIncome = 'setMortgageIncome',
    SetMortgageManualResidencePlace = 'setMortgageManualResidencePlace',
    GetMortgageContacts = 'getMortgageContacts',
    SetMortgageContacts = 'setMortgageContacts',
    SetMortgageApartmentAddress = 'setMortgageApartmentAddress',
    GetMortgageApartment = 'getMortgageApartment',
    SetMortgageApartment = 'setMortgageApartment',
    GetMortgageAdvance = 'getMortgageAdvance',
    SetMortgageAdvance = 'setMortgageAdvance',
    GetMortgageBanks = 'getMortgageBanks',
    SetMortgageBanks = 'setMortgageBanks',
    GetMortgageApplicationToConfirm = 'getMortgageApplicationToConfirm',
    GetMortgageHashedFilesToSign = 'getMortgageHashedFilesToSign',
    SendMortgageSignedItems = 'sendMortgageSignedItems',
    GetMortgagePackageApplication = 'getMortgagePackageApplication',
    CancelMortgagePackageApplication = 'cancelMortgagePackageApplication',
    CancelMortgagePackage = 'cancelMortgagePackage',
    ConfirmMortgageApplication = 'confirmMortgageApplication',
    DownloadMortgageDocument = 'downloadMortgageDocument',
    DownloadMortgageApplicationDocument = 'downloadMortgageApplicationDocument',
    PartnerRefuseMortgage = 'partnerRefuseMortgage',
    PartnerProposeMortgage = 'partnerProposeMortgage',
    PartnerIssueMortgage = 'partnerIssueMortgage',
}

const isStandaloneMortgageEnabled = process.env.PUBLIC_SERVICES_STANDALONE_MORTGAGE_IS_ENABLED === 'true'

const routes: AppRoute[] = isStandaloneMortgageEnabled
    ? [
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage',
              action: ServiceActions.GetMortgageServiceInfo,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/categories',
              action: ServiceActions.GetMortgageCategories,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/marital-status',
              action: ServiceActions.GetMortgageMaritalStatus,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/package',
              action: ServiceActions.CreateMortgagePackage,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/share',
              action: ServiceActions.ShareMortgage,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/verify',
              action: ServiceActions.VerifyMortgage,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.DELETE,
              path: '/api/:apiVersion/public-service/mortgage/reject',
              action: ServiceActions.RejectMortgage,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/children/number',
              action: ServiceActions.GetMortgageChildrenNumber,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/children/number',
              action: ServiceActions.SetMortgageChildrenNumber,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/children',
              action: ServiceActions.GetMortgageChildren,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/children',
              action: ServiceActions.SetMortgageChildren,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/real-estate',
              action: ServiceActions.GetMortgageRealEstate,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/real-estate/manual',
              action: ServiceActions.GetMortgageManualRealEstate,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/income',
              action: ServiceActions.GetMortgageIncome,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/income',
              action: ServiceActions.SetMortgageIncome,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/manual-residence-place',
              action: ServiceActions.SetMortgageManualResidencePlace,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/contacts',
              action: ServiceActions.GetMortgageContacts,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/contacts',
              action: ServiceActions.SetMortgageContacts,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/mortgage-apartment-address',
              action: ServiceActions.SetMortgageApartmentAddress,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/apartment',
              action: ServiceActions.GetMortgageApartment,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/apartment',
              action: ServiceActions.SetMortgageApartment,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/mortgage-apartment',
              action: ServiceActions.SetMortgageApartment,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/advance',
              action: ServiceActions.GetMortgageAdvance,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/advance',
              action: ServiceActions.SetMortgageAdvance,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/banks',
              action: ServiceActions.GetMortgageBanks,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.PATCH,
              path: '/api/:apiVersion/public-service/mortgage/banks',
              action: ServiceActions.SetMortgageBanks,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/application',
              action: ServiceActions.GetMortgageApplicationToConfirm,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/package/applications/signing',
              action: ServiceActions.GetMortgageHashedFilesToSign,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/package/applications/send',
              action: ServiceActions.SendMortgageSignedItems,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/package/application/:applicationId',
              action: ServiceActions.GetMortgagePackageApplication,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.DELETE,
              path: '/api/:apiVersion/public-service/mortgage/package/application/:applicationId',
              action: ServiceActions.CancelMortgagePackageApplication,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.DELETE,
              path: '/api/:apiVersion/public-service/mortgage/package',
              action: ServiceActions.CancelMortgagePackage,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/mortgage/package/application/:applicationId/processing',
              action: ServiceActions.ConfirmMortgageApplication,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/package/document/:loadActionType/download',
              action: ServiceActions.DownloadMortgageDocument,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.GET,
              path: '/api/:apiVersion/public-service/mortgage/package/application/:applicationId/document/:loadActionType/download',
              action: ServiceActions.DownloadMortgageApplicationDocument,
              auth: DEFAULT_USER_AUTH,
              headers: DEFAULT_USER_HEADERS,
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/partner/mortgage/application/refuse',
              action: ServiceActions.PartnerRefuseMortgage,
              auth: [
                  {
                      sessionType: SessionType.Partner,
                      version: ActionVersion.V1,
                      scopes: {
                          [PartnerScopeType.mortgage]: [PartnerMortgageScope.All],
                      },
                  },
              ],
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/partner/mortgage/application/proposal',
              action: ServiceActions.PartnerProposeMortgage,
              auth: [
                  {
                      sessionType: SessionType.Partner,
                      version: ActionVersion.V1,
                      scopes: {
                          [PartnerScopeType.mortgage]: [PartnerMortgageScope.All],
                      },
                  },
                  {
                      sessionType: SessionType.Partner,
                      version: ActionVersion.V2,
                      scopes: {
                          [PartnerScopeType.mortgage]: [PartnerMortgageScope.All],
                      },
                  },
                  {
                      sessionType: SessionType.Partner,
                      version: ActionVersion.V3,
                      scopes: {
                          [PartnerScopeType.mortgage]: [PartnerMortgageScope.All],
                      },
                  },
              ],
          },
          {
              method: HttpMethod.POST,
              path: '/api/:apiVersion/public-service/partner/mortgage/issue',
              action: ServiceActions.PartnerIssueMortgage,
              auth: [
                  {
                      sessionType: SessionType.Partner,
                      version: ActionVersion.V1,
                      scopes: {
                          [PartnerScopeType.mortgage]: [PartnerMortgageScope.All],
                      },
                  },
              ],
          },
      ]
    : []

export default routes
